meta = {'DDI': {'columns': [{'field': 'PhoneNumberStart',
                      'title': 'Phone Number Start',
                      'width': '14em'},
                     {'field': 'cid', 'title': 'Cid', 'width': '22em'},
                     {'field': 'RangeLength',
                      'title': 'Range Length',
                      'width': '4em'},
                     {'field': 'Status', 'title': 'Status', 'width': '0em'}],
         'idx': 'cid',
         'model': {'fields': {'PhoneNumberStart': {'type': 'string'},
                              'RangeLength': {'type': 'number'},
                              'Status': {'type': 'string'},
                              'cid': {'type': 'string'}}}},
 'Enterprise': {'columns': [{'field': 'EID', 'title': 'Eid', 'width': '8em'},
                            {'field': 'count_User',
                             'title': 'CountUser',
                             'width': '5em'},
                            {'field': 'cid',
                             'title': 'Cid',
                             'width': '16em'},
                            {'field': 'EnterpriseName',
                             'title': 'Enterprise Name',
                             'width': '20em'},
                            {'field': 'City',
                             'title': 'City',
                             'width': '8em'}],
                'ico': 'fa-book',
                'idx': 'cid',
                'model': {'fields': {'City': {'type': 'string'},
                                     'EID': {'type': 'string'},
                                     'EnterpriseName': {'type': 'string'},
                                     'cid': {'type': 'string'},
                                     'count_User': {'type': 'number'}}}},
 'Location': {'columns': [{'field': 'extServiceid',
                           'title': 'Ext Serviceid',
                           'width': '15em'},
                          {'field': 'cid', 'title': 'Cid', 'width': '23em'},
                          {'field': 'GroupName',
                           'title': 'Group Name',
                           'width': '11em'},
                          {'field': 'DDI', 'title': 'Ddi', 'width': '22em'},
                          {'field': 'City', 'title': 'City', 'width': '8em'},
                          {'field': 'Street',
                           'title': 'Street',
                           'width': '9em'}],
              'idx': 'cid',
              'model': {'fields': {'City': {'type': 'string'},
                                   'DDI': {'type': 'string'},
                                   'GroupName': {'type': 'string'},
                                   'Street': {'type': 'string'},
                                   'cid': {'type': 'string'},
                                   'extServiceid': {'type': 'string'}}}},
 'Number': {'columns': [{'field': 'ActivationTicket',
                         'title': 'Activation Ticket',
                         'width': '0em'},
                        {'field': 'EID', 'title': 'Eid', 'width': '8em'},
                        {'field': 'NrStatus',
                         'title': 'Nr Status',
                         'width': '10em'},
                        {'field': 'PhoneNumber',
                         'title': 'Phone Number',
                         'width': '14em'},
                        {'field': 'PhoneNumberInt',
                         'title': 'Phone Number Int',
                         'width': '13em'},
                        {'field': 'cid', 'title': 'Cid', 'width': '19em'},
                        {'field': 'cid2', 'title': 'Cid2', 'width': '16em'},
                        {'field': 'comments',
                         'title': 'Comments',
                         'width': '0em'},
                        {'field': 'creation_time',
                         'filterable': {'ui': 'datetimepicker'},
                         'format': '{0: yyyy-MM-dd HH:mm:ss}',
                         'title': 'Creation Time',
                         'width': '21em'},
                        {'field': 'editor',
                         'title': 'Editor',
                         'width': '7em'},
                        {'field': 'extServiceid',
                         'title': 'Ext Serviceid',
                         'width': '15em'},
                        {'field': 'isLocked',
                         'title': 'Is Locked',
                         'width': '3em'},
                        {'field': 'last_updated',
                         'filterable': {'ui': 'datetimepicker'},
                         'format': '{0: yyyy-MM-dd HH:mm:ss}',
                         'title': 'Last Updated',
                         'width': '21em'},
                        {'field': 'logLevel',
                         'title': 'Log Level',
                         'width': '4em'},
                        {'field': 'path', 'title': 'Path', 'width': '3em'},
                        {'field': 'props', 'title': 'Props', 'width': '4em'},
                        {'field': 'roles', 'title': 'Roles', 'width': '0em'},
                        {'field': 'serviceid',
                         'title': 'Serviceid',
                         'width': '8em'},
                        {'field': 'statisticsDetails',
                         'title': 'Statistics Details',
                         'width': '4em'},
                        {'field': 'statisticsLastUpdate',
                         'filterable': {'ui': 'datetimepicker'},
                         'format': '{0: yyyy-MM-dd HH:mm:ss}',
                         'title': 'Statistics Last Update',
                         'width': '21em'},
                        {'field': 'statusService',
                         'title': 'Status Service',
                         'width': '3em'}],
            'idx': 'cid',
            'model': {'fields': {'ActivationTicket': {'type': 'string'},
                                 'EID': {'type': 'string'},
                                 'NrStatus': {'type': 'string'},
                                 'PhoneNumber': {'type': 'string'},
                                 'PhoneNumberInt': {'type': 'number'},
                                 'author': {'type': 'string'},
                                 'cid': {'type': 'string'},
                                 'cid2': {'type': 'string'},
                                 'comments': {'type': 'string'},
                                 'creation_time': {'type': 'date'},
                                 'editor': {'type': 'string'},
                                 'extServiceid': {'type': 'string'},
                                 'isLocked': {'type': 'number'},
                                 'last_updated': {'type': 'date'},
                                 'logLevel': {'type': 'number'},
                                 'path': {'type': 'string'},
                                 'props': {'type': 'string'},
                                 'roles': {'type': 'string'},
                                 'serviceid': {'type': 'number'},
                                 'statisticsLastUpdate': {'type': 'date'},
                                 'statusService': {'type': 'number'}}}},
 'Ticket': {'columns': [{'field': 'status',
                         'title': 'Status',
                         'width': '3em'},
                        {'field': 'last_updated',
                         'title': 'Last Updated',
                         'width': '21em'},
                        {'field': 'title',
                         'title': 'Title',
                         'width': '30em'},
                        {'field': 'cid', 'title': 'Cid', 'width': '8em'},
                        {'field': 'cid2', 'title': 'Cid2', 'width': '8em'},
                        {'field': 'extTicketid',
                         'title': 'Ext Ticketid',
                         'width': '20em'},
                        {'field': 'serviceid',
                         'title': 'Serviceid',
                         'width': '12em'},
                        {'field': 'ticketid',
                         'title': 'Ticketid',
                         'width': '8em'},
                        {'field': 'step', 'title': 'Step', 'width': '3em'},
                        {'field': 'task', 'title': 'Task', 'width': '8em'},
                        {'field': 'creation_time',
                         'filterable': {'ui': 'datetimepicker'},
                         'format': '{0: yyyy-MM-dd HH:mm:ss}',
                         'title': 'Creation Time',
                         'width': '21em'}],
            'idx': 'ticketid',
            'model': {'fields': {'cid': {'type': 'string'},
                                 'cid2': {'type': 'string'},
                                 'creation_time': {'type': 'date'},
                                 'extTicketid': {'type': 'string'},
                                 'last_updated': {'type': 'string'},
                                 'serviceid': {'type': 'string'},
                                 'status': {'type': 'number'},
                                 'step': {'type': 'string'},
                                 'task': {'type': 'string'},
                                 'ticketid': {'type': 'number'},
                                 'title': {'type': 'string'}}}},
 'TicketLog': {'columns': [{'field': 'id',
                            'hidden': True,
                            'title': 'Id',
                            'width': '8em'},
                           {'field': 'date',
                            'title': 'Date',
                            'width': '5em'},
                           {'field': 'log', 'title': 'Log', 'width': '40em'},
                           {'field': 'logLevel',
                            'title': 'Log Level',
                            'width': '4em'},
                           {'field': 'ts', 'title': 'Ts', 'width': '15em'}],
               'idx': 'ts',
               'model': {'fields': {'date': {'type': 'string'},
                                    'id': {'type': 'number'},
                                    'log': {'type': 'string'},
                                    'logLevel': {'type': 'number'},
                                    'ts': {'type': 'number'}}}},
 'User': {'columns': [{'field': 'Alias', 'title': 'Alias', 'width': '40em'},
                      {'field': 'cid', 'title': 'Cid', 'width': '30em'},
                      {'field': 'Lastname',
                       'title': 'Lastname',
                       'width': '16em'},
                      {'field': 'Firstname',
                       'title': 'Firstname',
                       'width': '17em'},
                      {'field': 'Extension',
                       'title': 'Extension',
                       'width': '5em'},
                      {'field': 'UserID', 'title': 'User', 'width': '40em'}],
          'idx': 'cid',
          'model': {'fields': {'Alias': {'type': 'string'},
                               'DDI': {'type': 'string'},
                               'Extension': {'type': 'string'},
                               'Firstname': {'type': 'string'},
                               'Lastname': {'type': 'string'},
                               'UserID': {'type': 'string'},
                               'cid': {'type': 'string'}}}},
 'childs_by_parent': [['Ticket', ['TicketLog']],
                      ['TicketLog', []],
                      ['Enterprise',
                      ['Ticket', 'DDI', 'Location', 'User']],
                      ['DDI', ['Ticket']],
                      ['Location', ['Ticket', 'User', 'Number']],
                      ['User', ['Ticket']],
                      ['Number', []]],
 'top': 'Enterprise'}

